### ISSUE TITLE
[Bug]: Dashboard doesn't load chain view with docker image "latest"

### ISSUE THREAD

**Issue by adrian-grassl** [iotaledger/wasp-dashboard#450]
### Issue description

When using the latest docker image of wasp-dashboard (`image: iotaledger/wasp-dashboard:latest`), the view of a specific chain is not loaded properly. You can see it's loaded initially, but the view disappears again immediately.

With image version 0.1.5 (`image: iotaledger/wasp-dashboard:0.1.5`) this is no issue.

I am using the local-setup compose file in the most recent wasp release [v0.6.0-alpha.1](https://github.com/iotaledger/wasp/blob/v0.6.0-alpha.1/tools/local-setup/docker-compose.yml)

### Expected behaviour

See issue description

### Actual behaviour

See issue description

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

See issue description

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Dr-Electron** [comment]
I didn't try, but is this issue still relevant?

**Comment by adrian-grassl** [comment]
Resolved
